# Exercícios

## 1) Crie uma classe que irá modelar características geométricas de um círculo. Deverá implementar os métodos:
        -> Área 
        -> Perímetro
## Utilize atributos de classe e de instância apropriados. Crie um inicializador e métodos.
$area = \pi*r^2$

$perimetro = 2*\pi*r$

In [1]:
# resposta 1
import math
class Circulo:

    def __init__(self, raio):
        self.raio = raio
        self.pi   = 3.14
       
    def area(self):
        return math.sqrt(self.raio) * self.pi
            
    def perimetro(self):
        return 2 * self.raio * self.pi

In [2]:
# Instanciamento
obj = Circulo(5)
obj.raio
area = obj.area()
perimetro = obj.perimetro()

print(area)
print(perimetro)

7.021253449349341
31.400000000000002


## 2) Crie uma classe chamada matemática que conterá duas classes: trigonométrica e algébrica. Defina dentro da classe trigonométrica as seguintes funções:
    -> seno
    -> cosseno
    -> tangente
## Defina dentro da classe algébrica as seguintes funções: 
    -> soma
    -> subtração
    -> multiplicação
    -> divisão
## Cada função deverá receber array e retornar array

In [28]:
# resposta 2
import math
import numpy as np

class Matematica(object):       
        
    class Trigonometrica(object):

        def __init__(self):
            self.Listanumero = np.array(object.ListaNumero)

        def seno(self):
            return math.sin(self.ListaNumero)
           
        def cosseno(self):
            return math.cos(self.ListaNumero)

        def tangente(self):
            return math.tan(self.ListaNumero)
    
    class Algebrica(object):

        def __init__(self,ListaNumero ):
            self.ListaNumero = ListaNumero

        def soma(self):
            soma = 0
            for self.ListaNumero in lista:
                soma += self.ListaNumero
                return soma

        def subtracao(self):
            sub = 0
            for self.ListaNumero in lista:
                sub -= self.ListaNumero
                return sub      

        def multiplicacao(self):
            mult = 0
            for self.ListaNumero in lista:
                mult *= self.ListaNumero
                return mult        

        def divisao(self):
            div = 0
            for self.ListaNumero in lista:
                div /= self.ListaNumero
                return div
        

In [29]:
# Instanciamento
lista = [1,2,3]
instMat = Matematica().Trigonometrica(lista).seno()
print(instMat)

TypeError: __init__() takes 1 positional argument but 2 were given

## 3) Dados 2 arrays, A e B, remova de A todo elemento pertencente a B

In [27]:
# resposta 3
import numpy as np
A = np.array([1,2,3,4,5])
B = np.array([5,3])
C = np.setdiff1d(A,B)
C



array([1, 2, 4])

## 4) Crie uma função que recebe um array, um inteiro n e um inteiro m e que retorne outro array contendo elementos que estão entre os valores n e m do array recebido pela função. 

In [23]:
# resposta 4
import numpy as np
def Exec4(arr,n,m):  
#outroArr = np.where((range(arr),n,m))
#arr = np.array([5,4,8])
#arr[2:6]
#for i in arr:
#    print(i)       
#   return(outroArr)
    outroArr = np.array(arr)
    a = np.where(n == outroArr)
    b = np.where(m == outroArr)
    resultado = outroArr[n-1:m]
    
    return resultado


lista = np.array([4,5,6,3])
Exec4(lista,1,2)

array([4, 5])

## 5) Escreva uma função que recebe um vetor e um inteiro. Compare cada elemento desse vetor com o número inteiro. Se o elemento do vetor for maior, retorne a diferença entre eles, caso contrário, retorne a soma.

In [34]:
# resposta 5
def Exec5(lista,numero):
   # np.in1d(lista,numero)
    return(np.where(numero>lista, numero+lista, numero-lista))

lista = np.array([1,2,3])
Exec5(lista,3)

array([4, 5, 0])

## 6) Dada a seguinte matriz:
    -> [ 8,1,7
         4,3,9
         5,2,6]
## escreva uma função que retorne a matriz ordenada por um dos eixos. utilize a função built-in sorted para realizar a ordenação

In [57]:
# resposta 6
import numpy as np 
def Exec6(matriz):
    arr = np.sort(matriz, axis = 0)         
    return(arr)


matriz = np.array([[8,1,7], [4,3,9],[5,2,6]])     
Exec6(matriz)

array([[4, 1, 6],
       [5, 2, 7],
       [8, 3, 9]])